CHARACTERISTICS = {
    0x0001: "Image only, Windows CE, and Microsoft Windows NT and later. This indicates that the file does not contain base relocations and must therefore be loaded at its preferred base address. If the base address is not available, the loader reports an error. The default behavior of the linker is to strip base relocations from executable (EXE) files.",
    0x0002: "Image only. This indicates that the image file is valid and can be run. If this flag is not set, it indicates a linker error.",
    0x0004: "COFF line numbers have been removed. This flag is deprecated and should be zero.",
    0x0008: "COFF symbol table entries for local symbols have been removed. This flag is deprecated and should be zero.",
    0x0010: "Obsolete. Aggressively trim working set. This flag is deprecated for Windows 2000 and later and must be zero.",
    0x0020: "Application can handle > 2-GB addresses.",
    0x0080: "Little endian: the least significant bit (LSB) precedes the most significant bit (MSB) in memory. This flag is deprecated and should be zero.",
    0x0100: "Machine is based on a 32-bit-word architecture.",
    0x0200: "Debugging information is removed from the image file.",
    0x0400: "If the image is on removable media, fully load it and copy it to the swap file.",
    0x0800: "If the image is on network media, fully load it and copy it to the swap file.",
    0x1000: "The image file is a system file, not a user program.",
    0x2000: "The image file is a dynamic-link library (DLL). Such files are considered executable files for almost all purposes, although they cannot be directly run.",
    0x4000: "The file should be run only on a uniprocessor machine.",
    0x8000: "Big endian: the MSB precedes the LSB in memory. This flag is deprecated and should be zero."
}

MACHINES = {
  0x0: "The content of this field is assumed to be applicable to any machine type",
  0x1d3: "Matsushita AM33",
  0x8664: "x64",
  0x1c0: "ARM little endian",
  0xaa64: "ARM64 little endian",
  0x1c4: "ARM Thumb-2 little endian",
  0xebc: "EFI byte code",
  0x14c: "Intel 386 or later processors and compatible processors",
  0x200: "Intel Itanium processor family",
  0x6232: "LoongArch 32-bit processor family",
  0x6264: "LoongArch 64-bit processor family",
  0x9041: "Mitsubishi M32R little endian",
  0x266: "MIPS16",
  0x366: "MIPS with FPU",
  0x466: "MIPS16 with FPU",
  0x1f0: "Power PC little endian",
  0x1f1: "Power PC with floating point support",
  0x166: "MIPS little endian",
  0x5032: "RISC-V 32-bit address space",
  0x5064: "RISC-V 64-bit address space",
  0x5128: "RISC-V 128-bit address space",
  0x1a2: "Hitachi SH3",
  0x1a3: "Hitachi SH3 DSP",
  0x1a6: "Hitachi SH4",
  0x1a8: "Hitachi SH5",
  0x1c2: "Thumb",
  0x169: "MIPS little-endian WCE v2"
}

DLLS = {
    0x0100: "Image is NX compatible.",
    0x0200: "Isolation aware, but do not isolate the image.",
    0x0400: "Does not use structured exception (SE) handling. No SE handler may be called in this image.",
    0x0800: "Do not bind the image.",
    0x1000: "Image must execute in an AppContainer.",
    0x2000: "A WDM driver.",
    0x4000: "Image supports Control Flow Guard.",
    0x8000: "Terminal Server aware."
}

SUBSYSTEMS = {
    0: "An unknown subsystem",
    1: "Device drivers and native Windows processes",
    2: "The Windows graphical user interface (GUI) subsystem",
    3: "The Windows character subsystem",
    5: "The OS/2 character subsystem",
    7: "The Posix character subsystem",
    8: "Native Win9x driver",
    9: "Windows CE",
    10: "An Extensible Firmware Interface (EFI) application",
    11: "An EFI driver with boot services",
    12: "An EFI driver with run-time services",
    13: "An EFI ROM image",
    14: "XBOX",
    16: "Windows boot application."
}

SECTIONS = {
    0x00000008: "The section should not be padded to the next boundary. This flag is obsolete and is replaced by IMAGE_SCN_ALIGN_1BYTES. This is valid only for object files.",
    0x00000020: "The section contains executable code.",
    0x00000040: "The section contains initialized data.",
    0x00000080: "The section contains uninitialized data.",
    0x00000100: "Reserved for future use.",
    0x00000200: "The section contains comments or other information. The .drectve section has this type. This is valid for object files only.",
    0x00000800: "The section will not become part of the image. This is valid only for object files.",
    0x00001000: "The section contains COMDAT data. For more information, see COMDAT Sections (Object Only). This is valid only for object files.",
    0x00008000: "The section contains data referenced through the global pointer (GP).",
    0x00020000: "Reserved for future use.",
    0x00020000: "Reserved for future use.",
    0x00040000: "Reserved for future use.",
    0x00080000: "Reserved for future use.",
    0x00100000: "Align data on a 1-byte boundary. Valid only for object files.",
    0x00200000: "Align data on a 2-byte boundary. Valid only for object files.",
    0x00300000: "Align data on a 4-byte boundary. Valid only for object files.",
    0x00400000: "Align data on an 8-byte boundary. Valid only for object files.",
    0x00500000: "Align data on a 16-byte boundary. Valid only for object files.",
    0x00600000: "Align data on a 32-byte boundary. Valid only for object files.",
    0x00700000: "Align data on a 64-byte boundary. Valid only for object files.",
    0x00800000: "Align data on a 128-byte boundary. Valid only for object files.",
    0x00900000: "Align data on a 256-byte boundary. Valid only for object files.",
    0x00A00000: "Align data on a 512-byte boundary. Valid only for object files.",
    0x00B00000: "Align data on a 1024-byte boundary. Valid only for object files.",
    0x00C00000: "Align data on a 2048-byte boundary. Valid only for object files.",
    0x00D00000: "Align data on a 4096-byte boundary. Valid only for object files.",
    0x00E00000: "Align data on an 8192-byte boundary. Valid only for object files.",
    0x01000000: "The section contains extended relocations.",
    0x02000000: "The section can be discarded as needed.",
    0x04000000: "The section cannot be cached.",
    0x08000000: "The section is not pageable.",
    0x10000000: "The section can be shared in memory.",
    0x20000000: "The section can be executed as code.",
    0x40000000: "The section can be read.",
    0x80000000: "The section can be written to."
}